# Generated by Django 5.1.1 on 2024-10-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_gender_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_raise',
            name='select_order',
        ),
    ]
