# Generated by Django 5.1.1 on 2024-10-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_ticket_raise_select_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_raise',
            old_name='order',
            new_name='select_order',
        ),
    ]
