# Generated by Django 5.1.1 on 2024-10-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_order_ticket_raise_select_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantname',
            name='restaurant_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_raise',
            name='attach_file',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
