# Generated by Django 5.1.1 on 2024-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_customuser_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_raise',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], max_length=100, null=True),
        ),
    ]
