# Generated by Django 5.1.1 on 2024-10-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_order_resturant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('about', models.CharField(max_length=400, null=True)),
                ('issue', models.CharField(max_length=400, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
