# Generated by Django 5.1.1 on 2024-10-27 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_data',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
