# Generated by Django 5.1.1 on 2024-10-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_restaurantname_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantname',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
