# Generated by Django 5.1.1 on 2024-11-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_restaurantname_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
    ]
