# Generated by Django 5.1.1 on 2024-11-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_order_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tag',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
