# Generated by Django 5.1.1 on 2024-11-07 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_order_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.JSONField(blank=True, default=list, null=True)),
                ('device', models.JSONField(blank=True, default=list, null=True)),
                ('platform', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.fcmtoken'),
        ),
    ]
