# Generated by Django 5.1.1 on 2024-11-07 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_fcmtoken_customuser_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fcm_token',
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
