# Generated by Django 5.1.1 on 2024-11-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_customuser_fcm_token_fcmtoken_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='device',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='fcm_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='platform',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
