# Generated by Django 5.1.1 on 2024-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_fcmdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.CharField(max_length=500, null=True)),
                ('privacy', models.CharField(max_length=500, null=True)),
                ('termsandcondition', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
