# Generated by Django 5.1.1 on 2024-11-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_termsandconditions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='faq',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='privacy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='termsandcondition',
            field=models.TextField(null=True),
        ),
    ]
