# Generated by Django 5.1.1 on 2024-11-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_order_delivery_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermsAndConditions',
        ),
    ]
