# Generated by Django 5.1.1 on 2024-11-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_delete_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantname',
            name='restaurantoff',
            field=models.DateField(null=True),
        ),
    ]
