# Generated by Django 5.1.1 on 2024-11-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_restaurantname_restaurantoff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantname',
            old_name='restaurantoff',
            new_name='resturantoff',
        ),
    ]
