# Generated by Django 5.1.1 on 2024-11-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_order_resturant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='resturant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resturant_data', to='myapp.restaurantname'),
        ),
    ]
